name: Release
on:
    push:
        branches: [main]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    release:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository
        
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true

            - name: Get app version
              id: get-version
              uses: colathro/crate-version@1.0.0
              with:
                file: "./Cargo.toml"

            - name: Push tag
              uses: EndBug/latest-tag@latest
              with:
                ref: "v${{ steps.get-version.outputs.version }}"

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                workspaces: './src -> target'
              
            - name: Install tauri-cli
              uses: baptiste0928/cargo-install@v3
              with:
                crate: tauri-cli
                version: 1.5.1
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 'latest'
                cache: 'yarn'
                cache-dependency-path: './view/yarn.lock'

            - name: Build executable
              env:
                TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              run: cargo tauri build

            - name: Artifact preparation
              run: ./scripts/create_latest.ps1

            - name: Publish artifacts
              uses: ncipollo/release-action@v1
              with:
                artifacts: ./target/release/SpaceHoPHelper14.exe
                body: See the assets to download and install this version.
                tag: "v${{ steps.get-version.outputs.version }}"
            
            - name: Setup Pages
              uses: actions/configure-pages@v5
            
            - uses: actions/upload-pages-artifact@v3
              with:
                path: ./target/publish

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4